### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by mpaepper** [beyarkay/vvim#1]
Hi @beyarkay ,

just wanted to shout out that I really like this project. 

Do you have any screenshots about the project, in particular the gloves / sensors you use etc?
How would I get started to try this out myself?

Thank you
Marc

**Comment by beyarkay** [comment]
Hey, Thanks! Really appreciate it.

I don't have anything official written out I'm afraid. From February this year I've been working on this project for my Computer Science honour's degree, so the focus has changed a bit. But I'll write out what I can remember in case that helps you. I'm also posting more regular updates on my Instagram @boydrkane so that might be helpful.

Also there are a few images in [img/images](https://github.com/beyarkay/vvim/tree/main/img/images) that might be useful, although I'll admit it's not terribly well organised. Specifically [this side view](https://github.com/beyarkay/vvim/blob/main/img/images/glove_V1_side.jpg), and [this top-down view](https://github.com/beyarkay/vvim/blob/main/img/images/glove_V1.jpeg). Both are of Version 1.

So what is in this repo is essentially Version 0(using a black off-the-shelf material glove) and Version 1(using a blue 3D printed glove), and I'm currently working on Version 2 but have some restrictions set by my University in terms of what I can share publicly. I'll see if I can get around them, but it might take some time. Version 2 is quite different, but I'll give details below about Version 1 and it's flaws so you can make your own judgement

## Version 1

In terms of materials for version 1 (version 0 isn't really worth bothering with):
- Three 2.2" flex sensors per finger, these are the brown striped flexible pieces you can see going across my knuckles. These are quite expensive, *very* easy to melt/break when soldering them, and sometimes hard to get ahold of. The first sensor I mounted across the knuckle where the finger joins the base of the hand, and the second sensor I mounted at the first knuckle, and the third sensor at the final knuckle. I didn't have any sensors on my thumb for simplicity.
- An arduino of some sort to act as the brain for the whole thing (I've used an Uno for testing, and then a Nano 3.3v BLE once I was happy with the wiring and circuitry
- A 16-to-1 multiplexor. The flex sensors output one analog signal each, and with 3 sensors on 4 fingers that results in 12 analog inputs, but most arduino's don't have 12 analog input pins. The 16-to-1 multiplexor converts the 12 inputs into one input and 4 input selector pins, which you can set HIGH / LOW to choose which input you'd like to read from. I can't find the part number of the one I used, but will send another comment when I do.

I'm afraid my computer has crashed recently and I lost the files for the 3D printed components.

Version 1 worked pretty well, but had a lot of trouble distinguishing between certain letters because of how the sensors were laid out. Basically, the sensors only picked up on up/down movement which meant distinguishing between letters like `j` and `h` (which are pressed by the same finger, but just moved left/right a little bit) was basically impossible.

Also, the 3D printed components were uncomfortable, *increadibly* difficult to design well, and having a load of little pieces made the glove tricky to take on / off.

## Version 2

Version 2 (which I'll try to push to this repo soon) is quite different in terms of goals and components. The goal is no longer to try mimic a qwerty keyboard, but rather to recognize arbitrary 2 handed gestures made in the air and classify them into keystrokes. The hope is that this will be easier (since I can choose gestures based on how easily a statistical model can distinguish them) and more useful (since you will be able to 'type' in the air, while walking or seated or wherever you want)

To this goal, the 12 flex sensors are replaced by Triple Axis Accelerometers `ADXL335`. One sensor on each fingertip (including the thumb). Each sensor measures linear acceleration along the 3 coordinate axes X, Y, and Z. These 15 inputs (X, Y, and Z for the five fingers) are again sent through the same 16-to-1 and then to an Arduino Nano. I am about to start training models and collecting training data.

Hope that helps! feel free to close this issue or leave another comment if you've got any other questions.

**Comment by mpaepper** [comment]
Thank you for the details and sorry I haven't replied earlier.

Again, it's a really cool project and I enjoyed getting some more insights on the practicality of using it.

Hopefully at some point in the future something like this will be usable in practice - I would totally use it.
